Switch to optimized ffsl supported on more platforms
In file included from Source/GmmLib/TranslationTable/GmmAuxTable.cpp:30:
Source/GmmLib/TranslationTable/../TranslationTable/GmmUmdTranslationTable.h: In function ‘int _BitScanForward(uint32_t*, uint32_t)’:
Source/GmmLib/TranslationTable/../TranslationTable/GmmUmdTranslationTable.h:63:9: error: ‘ffsl’ was not declared in this scope
     i = ffsl(mask);
         ^~~~
Source/GmmLib/TranslationTable/../TranslationTable/GmmUmdTranslationTable.h:63:9: note: suggested alternative: ‘ffs’
     i = ffsl(mask);
         ^~~~
         ffs